[package]
name = "xfg"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
description = "eXtensible FrameGraph for `gfx_hal`"
license = "MIT/Apache-2.0"
repository = "https://github.com/omni-viral/xfg-rs"

[dependencies]
derivative = "1.0"
gfx-hal = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx", rev = "54fe14fbb" }
gfx-chain = { version = "0.1.0", git = "https://github.com/omni-viral/gfx-chain" }
log = "0.4"
relevant = "0.1"
smallvec = "0.4"

[dev-dependencies]
cgmath = "0.16"
env_logger = "0.5"
gfx-memory = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx-memory", rev = "9125d94e" }
winit = "0.11"

[workspace]
members = ["examples"]


[patch.'https://github.com/omni-viral/gfx-chain']
gfx-chain = { path = "../gfx-chain" }

[patch.'https://github.com/gfx-rs/gfx']
gfx-hal = { path = "../gfx/src/hal" }
