[package]
name = "xfg"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
description = "eXtensible FrameGraph for `gfx_hal`"
license = "MIT/Apache-2.0"
repository = "https://github.com/omni-viral/xfg-rs"

[dependencies]
bitflags = "1.0"
derivative = "1.0"
gfx-hal = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx", rev = "506ba0af0" }
log = "0.4"
relevant = "0.1"
smallvec = "0.4"

[dev-dependencies]
cgmath = "0.16"
env_logger = "0.5"
gfx-memory = { version = "0.1.0", git = "https://github.com/gfx-rs/gfx-memory", rev = "f7a8166" }
winit = "0.10"

[workspace]
members = ["examples"]
